version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_fastapi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fastapi_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3307:3306"         # <-- ESSENCIAL! Expondo a porta
    volumes:
      - mysql_data:/var/lib/mysql
    command: [
      "--default-authentication-plugin=mysql_native_password"
    ]

volumes:
  mysql_data:
